// registration
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const REQUEST_SIGN_IN_SUCCESS = 'REQUEST_SIGN_IN_SUCCESS';
export const REQUEST_SIGN_IN_FAILED = 'REQUEST_SIGN_IN_FAILED';
export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
export const REQUEST_SIGN_OUT_SUCCESS = 'REQUEST_SIGN_OUT_SUCCESS';
export const REQUEST_SIGN_OUT_FAILED = 'REQUEST_SIGN_OUT_FAILED';

// news
export const LOAD_ALL_NEWS = 'LOAD_ALL_NEWS';
export const LOAD_ALL_NEWS_SUCCESS = 'LOAD_ALL_NEWS_SUCCESS';
export const LOAD_ALL_NEWS_FAILED = 'LOAD_ALL_NEWS_FAILED';
export const CREATE_NEWS = 'CREATE_NEWS';
export const CREATE_NEWS_SUCCESS = 'CREATE_NEWS_SUCCESS';
export const CREATE_NEWS_FAILED = 'CREATE_NEWS_FAILED';
export const CLEAR_NEWS_ALERT_INFO = 'CLEAR_NEWS_ALERT_INFO';

// user
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILED = 'LOAD_USERS_FAILED';
export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS';
export const LOAD_USER_INFO_FAILED = 'LOAD_USER_INFO_FAILED';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILED = 'UPDATE_USER_INFO_FAILED';
